### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by DrSnowPengu** [Jona123/Warpalicious#1]
Hello 

There couple issues with this plugin wonder If you can fix it. 
When ever I /setwarp name it gives me this error message - https://gyazo.com/c8da0fdbe597e78a6f360a05ef39fecc
and also some how some of my warps are remove. I think there something wrong if the plugin and wonder If you can fix it.

Thank you.

**Comment by Jona123** [comment]
Hi!

Thanks for reporting your issue. I can't really do much without the stacktrace though. You can find the stacktrace in the console when a message like the one you posted appears.

**Comment by DrSnowPengu** [comment]
Hello are you able show me an example for stacktrace for the console and also is there way to create warp signs?

**Comment by Jona123** [comment]
Stacktraces in the console usually look like this: https://proxy.spigotmc.org/f93373f7573fdb8f0129eeebe4f3bc11243da38a?url=http%3A%2F%2Fi39.tinypic.com%2F2nk0013.png

I haven't added warp sign support yet. If you want it I can add it

**Comment by DrSnowPengu** [comment]
Sure thing and plugin needs to be fix. Now when players does /warp name it doesn't let you it said same message error. I think there are some bugs need to be fix.

**Comment by Jona123** [comment]
As I said: I would love to fix your issues, but I need to know what to fix and if you don't provide a stacktrace or detailed description of the problem I can't.

The stacktrace is the same as the error message that pops up in the console.
