### ISSUE TITLE
1.16.5 unable to invite/uninvite players

### ISSUE THREAD

**Issue by josiahkeeler** [Jona123/Warpalicious#13]
Not sure why this is broken. Unable to use tab complete for warpinfo and invite. Attempting to invite users  results in "That player has already been invited" even if they haven't. Checked warps.yml and nothing was updated in the values. Tried updating warps.yml manually and that did nothing too even after a full server restart. Not getting any errors in console.

**Comment by datdenkikniet** [comment]
Thanks for the report. Should be fixed by 5b6a7ea

You can find the new version on Spigot's website
